name: learning


on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: chekout out source
        uses: actions/checkout@v4

      - name: create text
        run: echo "hello world" > index.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: show txt
          path: /index.txt
